name: iris_app
description: A Flutter app for eye disease detection.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^14.7.1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  camera: ^0.10.0
  permission_handler: ^11.0.1
  lottie: ^3.3.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_shaders: ^0.1.2
  vector_math: ^2.1.4
  # Add packages for better platform support
  image_picker_for_web: ^3.0.1
  image_picker_android: ^0.8.8
  image_picker_ios: ^0.8.8
  camera_web: ^0.3.2
  camera_android: ^0.10.8
  camera_avfoundation: ^0.9.13
  path_provider: ^2.1.5
  web_socket_channel: ^2.0.0
  shared_preferences: ^2.0.0
  device_info_plus: ^9.1.2
  http: ^1.0.0
  provider: ^6.0.0
  flutter_secure_storage: ^8.0.0
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/eye.svg
    - assets/scan_transition.json
    - assets/icons/
    - assets/icons/conjunctivitis.svg
    - assets/icons/glaucoma.svg
    - assets/icons/cataract.svg
    - assets/icons/retinopathy.svg
  shaders:
    - assets/shaders/aurora.glsl
